global using ArrayType = LeXtudio.Metadata.Mutable.MutableArrayType;
global using AssemblyDefinition = LeXtudio.Metadata.Mutable.MutableAssemblyDefinition;
global using CustomAttribute = LeXtudio.Metadata.Mutable.MutableCustomAttribute;
global using CustomAttributeArgument = LeXtudio.Metadata.Mutable.MutableCustomAttributeArgument;
global using CustomAttributeNamedArgument = LeXtudio.Metadata.Mutable.MutableCustomAttributeNamedArgument;
global using EventDefinition = LeXtudio.Metadata.Mutable.MutableEventDefinition;
global using FieldDefinition = LeXtudio.Metadata.Mutable.MutableFieldDefinition;
global using FieldReference = LeXtudio.Metadata.Mutable.MutableFieldReference;
global using GenericInstanceMethod = LeXtudio.Metadata.Mutable.MutableGenericInstanceMethod;
global using Instruction = LeXtudio.Metadata.Mutable.MutableInstruction;
global using MethodDefinition = LeXtudio.Metadata.Mutable.MutableMethodDefinition;
global using MethodReference = LeXtudio.Metadata.Mutable.MutableMethodReference;
global using ModuleDefinition = LeXtudio.Metadata.Mutable.MutableModuleDefinition;
global using ModuleAttributes = LeXtudio.Metadata.Mutable.MutableModuleAttributes;
global using OpCodes = LeXtudio.Metadata.Mutable.MutableOpCodes;
global using ParameterDefinition = LeXtudio.Metadata.Mutable.MutableParameterDefinition;
global using PropertyDefinition = LeXtudio.Metadata.Mutable.MutablePropertyDefinition;
global using TypeDefinition = LeXtudio.Metadata.Mutable.MutableTypeDefinition;
global using TypeReference = LeXtudio.Metadata.Mutable.MutableTypeReference;
global using Obfuscar.Helpers;
global using System.Reflection;
