global using ArrayType = Obfuscar.Metadata.Mutable.MutableArrayType;
global using AssemblyDefinition = Obfuscar.Metadata.Mutable.MutableAssemblyDefinition;
global using CustomAttribute = Obfuscar.Metadata.Mutable.MutableCustomAttribute;
global using CustomAttributeArgument = Obfuscar.Metadata.Mutable.MutableCustomAttributeArgument;
global using CustomAttributeNamedArgument = Obfuscar.Metadata.Mutable.MutableCustomAttributeNamedArgument;
global using EventDefinition = Obfuscar.Metadata.Mutable.MutableEventDefinition;
global using FieldDefinition = Obfuscar.Metadata.Mutable.MutableFieldDefinition;
global using FieldReference = Obfuscar.Metadata.Mutable.MutableFieldReference;
global using GenericInstanceMethod = Obfuscar.Metadata.Mutable.MutableGenericInstanceMethod;
global using Instruction = Obfuscar.Metadata.Mutable.MutableInstruction;
global using MethodDefinition = Obfuscar.Metadata.Mutable.MutableMethodDefinition;
global using MethodReference = Obfuscar.Metadata.Mutable.MutableMethodReference;
global using ModuleDefinition = Obfuscar.Metadata.Mutable.MutableModuleDefinition;
global using ModuleAttributes = Obfuscar.Metadata.Mutable.MutableModuleAttributes;
global using OpCodes = Obfuscar.Metadata.Mutable.MutableOpCodes;
global using ParameterDefinition = Obfuscar.Metadata.Mutable.MutableParameterDefinition;
global using PropertyDefinition = Obfuscar.Metadata.Mutable.MutablePropertyDefinition;
global using TypeDefinition = Obfuscar.Metadata.Mutable.MutableTypeDefinition;
global using TypeReference = Obfuscar.Metadata.Mutable.MutableTypeReference;
global using Obfuscar.Helpers;
global using System.Reflection;
